version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8083:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: mikolatero/php5.6-fpm-alpine:latest
        volumes:
            - ./code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
